server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    location / {
        # 로컬: nginx는 도커 컨테이너, 스프링은 호스트(윈도우) 8080
        proxy_pass http://jobrecord-backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }
}
